version: '2'
services:
  storesampleapplication-app:
    image: storesampleapplication
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,swagger
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - SPRING_CLOUD_CONSUL_HOST=consul
      - SPRING_CLOUD_CONSUL_PORT=8500
      - SPRING_DATASOURCE_URL=jdbc:mysql://storesampleapplication-mysql:3306/storesampleapplication?useUnicode=true&characterEncoding=utf8&useSSL=false&useLegacyDatetimeCode=false&serverTimezone=UTC&createDatabaseIfNotExist=true
      - SPRING_SECURITY_OAUTH2_CLIENT_PROVIDER_OIDC_ISSUER_URI=http://keycloak:9080/auth/realms/jhipster
      - JHIPSTER_SLEEP=30 # gives time for other services to boot before the application
      - SPRING_DATA_JEST_URI=http://storesampleapplication-elasticsearch:9200
      - SPRING_ELASTICSEARCH_REST_URIS=http://storesampleapplication-elasticsearch:9200
      - KAFKA_BOOTSTRAPSERVERS=kafka:9092
      - JAVA_OPTS=-Djgroups.tcp.address=NON_LOOPBACK -Djava.net.preferIPv4Stack=true
  storesampleapplication-mysql:
    extends:
      file: mysql.yml
      service: storesampleapplication-mysql
  storesampleapplication-elasticsearch:
    extends:
      file: elasticsearch.yml
      service: storesampleapplication-elasticsearch
  kafka:
    extends:
      file: kafka.yml
      service: kafka
    environment:
      - KAFKA_ADVERTISED_HOST_NAME=kafka
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
  zookeeper:
    extends:
      file: kafka.yml
      service: zookeeper
  consul:
    extends:
      file: consul.yml
      service: consul

  consul-config-loader:
    extends:
      file: consul.yml
      service: consul-config-loader
  keycloak:
    extends:
      file: keycloak.yml
      service: keycloak
